---
- name: Create the Cloudflare DNS TXT record
  cloudflare_dns:
    domain: "{{ acmedns_cf_zone }}"
    record: "{{ item['value']['dns-01']['resource'] }}"
    type: TXT
    value: "{{ item['value']['dns-01']['resource_value'] }}"
    solo: true
    account_email: "{{ acmedns_cf_email }}"
    account_api_token: "{{ acmedns_cf_token }}"
    state: present
  with_dict: "{{ _acmedns_challenge['challenge_data'] }}"

- name: Wait
  wait_for:
    timeout: 30
  when: _acmedns_challenge is changed

- name: Validate the ACME DNS challenge
  acme_certificate:
    acme_version: 2
    acme_directory: "{{ acmedns_le_url }}"
    account_key_src: "{{ acmedns_le_accountkey }}"
    src: "{{ acmedns_le_dir }}/{{ acmedns_le_cn }}.csr"
    cert: "{{ acmedns_le_dir }}/{{ acmedns_le_cn }}.crt"
    fullchain: "{{ acmedns_le_dir }}/{{ acmedns_le_cn }}.pem"
    chain: "{{ acmedns_le_dir }}/{{ acmedns_le_cn }}-intermediate.pem"
    challenge: dns-01
    remaining_days: 60
    data: "{{ _acmedns_challenge }}"

- name: Delete the Cloudflare DNS TXT record
  cloudflare_dns:
    domain: "{{ acmedns_cf_zone }}"
    record: "{{ item['value']['dns-01']['resource'] }}"
    type: TXT
    account_email: "{{ acmedns_cf_email }}"
    account_api_token: "{{ acmedns_cf_token }}"
    state: absent
  with_dict: "{{ _acmedns_challenge['challenge_data'] }}"
...
