---
- name: Create the Route53 DNS TXT record
  route53:
    command: create
    zone: "{{ acmedns_r53_zone }}"
    record: "{{ item['value']['dns-01']['record'] }}"
    type: TXT
    ttl: 5
    value: "{{ item['value']['dns-01']['resource_value'] }}"
    aws_access_key: "{{ acmedns_r53_access_key }}"
    aws_secret_key: "{{ acmedns_r53_secret_key }}"
    overwrite: yes
    wait: yes
  with_dict: "{{ _acmedns_challenge['challenge_data'] }}"

- name: Wait
  wait_for:
    timeout: 30

- name: Validate the ACME DNS challenge
  acme_certificate:
    acme_version: 2
    acme_directory: "{{ acmedns_le_url }}"
    account_key_src: "{{ acmedns_le_accountkey }}"
    src: "{{ acmedns_le_dir }}/{{ acmedns_le_cn }}.csr"
    cert: "{{ acmedns_le_dir }}/{{ acmedns_le_cn }}.crt"
    fullchain: "{{ acmedns_le_dir }}/{{ acmedns_le_cn }}.pem"
    chain: "{{ acmedns_le_dir }}/{{ acmedns_le_cn }}-intermediate.pem"
    challenge: dns-01
    remaining_days: 60
    terms_agreed: true
    data: "{{ _acmedns_challenge }}"

- name: Delete the Route53 DNS TXT record
  route53:
    command: delete
    zone: "{{ acmedns_r53_zone }}"
    record: "{{ item['value']['dns-01']['resource'] }}"
    type: TXT
    ttl: 5
    value: "{{ item['value']['dns-01']['resource_value'] }}"
    aws_access_key: "{{ acmedns_r53_access_key }}"
    aws_secret_key: "{{ acmedns_r53_secret_key }}"
  with_dict: "{{ _acmedns_challenge['challenge_data'] }}"
...
